# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Check client workflow

on:
  pull_request:
    branches:
      - master

defaults:
  run:
    working-directory: client

jobs:
  test:
    name: Execute tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn --frozen-lockfile
      - run: yarn test --ci --silent
        env:
          SKIP_PREFLIGHT_CHECK: true
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn --frozen-lockfile
      - run: yarn lint
  typecheck:
    name: Check types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn --frozen-lockfile
      - run: yarn typecheck
  preview:
    name: Create app preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create app and Storybook builds
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn --frozen-lockfile
      - run: yarn build
        env:
          SKIP_PREFLIGHT_CHECK: true
      - run: yarn build-storybook

      - name: Deploy app to Netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.PROD_NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=client/build
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'

      - name: Deploy Storybook to Netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.PROD_NETLIFY_STORYBOOK_SITE_ID }}
        with:
          args: deploy --dir=client/storybook-static
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
      # - name: Crate preview URL file
      #   run: echo ${{ steps.netlify_preview.outputs.NETLIFY_URL }} > ./netlify.txt
      # - name: Save preview URL
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: netlify_url
      #     path: ./client/netlify.txt
