name: Deploy test workflow

on:
  push:
    branches:
      - develop

defaults:
  run:
    working-directory: client

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
      - uses: actions/checkout@v2

      - name: Create build
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn --frozen-lockfile
      - run: yarn build --if-present

      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.TEST_NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=client/build --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
      - name: Upload temporary path
        uses: actions/upload-artifact@v1
        with:
          name: netlify-url
          path: netlify-url.txt
