name: Deploy test workflow

on:
  push:
    branches:
      - develop

defaults:
  run:
    working-directory: client

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
      - uses: actions/checkout@v2

      - name: Create app and Storybook builds
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: yarn build-storybook

      - name: Deploy app to Netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.TEST_NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=client/build --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'

      - name: Deploy Storybook to Netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.TEST_NETLIFY_STORYBOOK_SITE_ID }}
        with:
          args: deploy --dir=client/storybook-static --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
